CREATE TABLE [Identity].[AspNetUsers] (
    [Id]                    NVARCHAR (450)     NOT NULL,
    [Email]                 NVARCHAR (256)     NULL,
    [EmailConfirmed]        BIT                NOT NULL,
    [PasswordHash]          NVARCHAR (MAX)     NULL,
    [SecurityStamp]         NVARCHAR (MAX)     NULL,
    [PhoneNumber]           NVARCHAR (MAX)     NULL,
    [PhoneNumberConfirmed]  BIT                NOT NULL,
    [TwoFactorEnabled]      BIT                NOT NULL,
    [LockoutEndDateUtc]     DATETIME           NULL,
    [LockoutEnabled]        BIT                NOT NULL,
    [AccessFailedCount]     INT                NOT NULL,
    [UserName]              NVARCHAR (256)     NOT NULL,
    [Name]                  NVARCHAR (MAX)     NULL,
    [AddressId]             INT                NULL,
    [PasswordResetRequired] BIT                CONSTRAINT [DF_AspNetUsers_PasswordResetRequired] DEFAULT ((0)) NULL,
    [ProviderUserTypeId]    INT                NULL,
    [CreatedByUserId]       NVARCHAR (128)     NULL,
    [CreatedDateTimeUtc]    DATETIME           NULL,
    [ModifiedByUserId]      NVARCHAR (128)     NULL,
    [ModifiedDateTimeUtc]   DATETIME           NULL,
    [IsDeleted]             BIT                NULL,
    [LegacyUserId]          INT                NULL,
    [LastLoginDateTimeUtc]  DATETIME           NULL,
    [IsSecureAccessUser]    BIT                NULL,
    [SecureAccessUserId]    INT                NULL,
    [ShowUserWizard]        BIT                NULL,
    [NormalizedUserName]    NVARCHAR (256)     NULL,
    [NormalizedEmail]       NVARCHAR (256)     NULL,
    [ConcurrencyStamp]      NVARCHAR (MAX)     NULL,
    [LockoutEnd]            DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_AspNetUsers] PRIMARY KEY CLUSTERED ([Id] ASC)
);

